name: mighty_games
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #BASE
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.1

  #UI
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  flutter_vector_icons: ^2.0.0
  lottie: ^3.3.1

  #STATE MANAGEMENT
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  #CONNECTIVITY
  http: ^1.2.2
  connectivity_plus: ^6.1.2
  package_info_plus: ^8.1.3
  share_plus: ^10.1.4
  store_redirect: ^2.0.3

  # WEB TOOLS
  flutter_inappwebview: ^6.1.5

  # ADS
  google_mobile_ads: ^5.2.0
  facebook_audience_network: ^1.0.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.2.9

  # LAUNCH URL
  url_launcher: ^6.3.1

  #Database
  shared_preferences: ^2.3.5

  fluttertoast: ^8.2.10
  html: ^0.15.5

  #Localization
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.7.0
  build_runner: ^2.4.14
  #flutter packages pub run build_runner build --delete-conflicting-outputs

  flutter_lints: ^5.0.0

dependency_overrides:
  connectivity_plus: ^5.0.1
  firebase_core: ^3.10.1
  intl: ^0.19.0
  flutter_inappwebview: ^6.1.0+1


flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/flag/
